<h3>About Us</h3>

<h4>Overview</h4>British Airways Virtual is one of the best virtual airlines out there. We have over 2000 real world British Airways routes and are constantly trying to be the best. We have been using several flight trackers over the years including: FSAirlines, VAFS and now phpVMS. We were always dominating the leaderboard of FSAirlines and were always in the top 50 on VAFS and now we have decided that we will thrive even more using phpVMS.<br><br> As a Virtual Airline, we have been going since September of 2012. We orrigionally started as an airline called FlyAirUK which has built up a very good reputation. We have intergrated this into British Airways Virtual as our training department.  

<br>
<h4>Our Goals</h4>
Our goal is to provide the most realistic and enjoyable experiance that is possible in the flight simulator world to all of our pilots through our staff team and services. We are striving to become one of the best virtual airlines in the world. Aiming to be the virtual airline that everyone is talking about in the virtual airline community. Our latest goal is migrating to a new flight tracking software and a complete new website, and grow to a bigger better future. 

<br>
<h4>What we offer!</h4>
As a member, you are eligable for:<br><br>1. Pilot Training - we offer training on lot's of aircraft ranging from all the default aircraft all the way to PMDG's 777.<br><br>2. ATC Training - we are able to train you from nothing all the way up to FSS(Flight Service Station)<br><br>3. VATSIM Training - we will train you how to fly on VATSIM and teach you how to communicate with ATC<br><br>4. Teamspeak server - We have a 24/7 teamspeak server where there is nearly always a staff member online who can help you with just about anything<br><br>5. Dedicated staff team - All of our staff here are willing to help. If you have any questions, ask them and they will help you or find someone who can.<br><br>6. News - we have a members-only forum, a members-only facebook group and a public facebook page. News, announcements and support can be found on all three.<br><br>7. Community, Most nights there are many people on Teamspeak and this is our community. We often fly together and on certain nights we do events such as the Saturday night flights.<br><br>8. Tours - We also have just released our first tour, the Worldwide tour. Pilots who complete this are given 50,000v$ bonus. We will be releasing a new tour soon...<br><br> <h3>For More Info, check here</h3><center> <!-- Facebook Badge START --><a href="https://www.facebook.com/britishairwaysvirtual" target="_TOP" style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;" title="British Airways Virtual">British Airways Virtual</a><span style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; line-height: 16px; font-variant: normal; font-style: normal; font-weight: normal; color: #555555; text-decoration: none;">&nbsp;|&nbsp;</span><a href="https://en-gb.facebook.com/advertising" target="_TOP" style="font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;" title="Make your own badge!">Promote your Page too</a><br/><a href="https://www.facebook.com/britishairwaysvirtual" target="_TOP" title="British Airways Virtual"><img src="https://badge.facebook.com/badge/589960297718075.2304.1803274923.png" style="border: 0px;" /></a><!-- Facebook Badge END --></center>